### ISSUE TITLE
Chart example doesn't work. Any ideas?

### ISSUE THREAD

**Issue by kramer65** [buger/goterm#16]
I tried the example on this page: https://github.com/buger/goterm/blob/master/examples/chart_example.go

But when running the program simply ends with no output. Any idea what I'm doing wrong?

Also, the code differs from the same example code in the readme, which doesn't run because it falsely tries to run `data.addColumn()` (with a lower case `a`), instead of the correct `data.AddColumn()` (with an upper case `A`).

**Comment by radbrawler** [comment]
What were the steps you followed .?
