### ISSUE TITLE
Using `unix.EOPNOTSUPP` will fail when build on windows.

### ISSUE THREAD

**Issue by rustatian** [buger/goterm#39]
Hey @buger , the last PR https://github.com/buger/goterm/pull/38 brought the change which prevented built for the Windows OS.
```go
if errors.Is(err, unix.EOPNOTSUPP) {
	return math.MaxInt
}
```
I suppose, that there are should be built tags, for Linux and separate `terminal_windows.go` w/o `Operation not supported on transport endpoint (EOPNOTSUPP)` constant.
Thanks :)

**Comment by rustatian** [comment]
@buger friendly ping 😃 https://github.com/buger/goterm/pull/41

**Comment by buger** [comment]
Fixed now
